### PR TITLE
[#170] Fixed scale being offset by an hour

### PR DESCRIPTION
**Pull request by alvyn279**
Scale now displays time from 9:30 AM to 4:00 PM.

### CODE REVIEW

**Comment by alvyn279** [comment]
> Is there a reason that we now want to show how we measured the constant? I.e showing the formula instead of just putting the product.
> 
> Looks good

yea makes it more verbose as to how we got to that number

**Comment by chris-baur** [comment]
> > Is there a reason that we now want to show how we measured the constant? I.e showing the formula instead of just putting the product.
> > Looks good
> 
> yea makes it more verbose as to how we got to that number

Ok, 👍

**Comment by Lercerss** [comment]
Actually, why are we subtracting one hour? Won't this fail when daylight savings changes again?

**Comment by alvyn279** [comment]
> Actually, why are we adding one hour? Won't this fail when daylight savings changes again?

Because Date object internally changes the given utc timestamp into local timezone, which involves daylight saving time. Until we're not going to interact with JS' Date interface, we'll have to change it every time dst changes, since we agreed for constant EDT timezone. 

Correct me if i'm not seeing a better solution

**Comment by Lercerss** [comment]
Have you looked into ways of instantiating a Date object with a given timezone instead of defaulting to the local one?

**Comment by Lercerss** [comment]
If that is not possible, I would prefer that we add/subtract the difference between the local timezone and EDT at runtime instead of hardcoding it to a value

**Comment by alvyn279** [comment]
reading this: https://stackoverflow.com/a/15171030

**Pull request merged**
